### ISSUE TITLE
Cannot access example image from the "Obtaining Coefficients" page

### ISSUE THREAD

**Issue by S-AQ** [parevalo/gee-ccdc-tools#1]
Hi Paulo, 

Thank you for bringing this wonderful algorithm to GEE and providing us with some nice documentation of it. 

I tried to work along with your examples in the [Obtaining coefficients, changes and synthetic images (API)](https://gee-ccdc-tools.readthedocs.io/en/latest/ccdc.html) page. 

In there you refer to an example image. This image is loaded using:
`// Load the results
var ccdc = ee.Image("projects/GLANCE/RESULTS/CHANGEDETECTION/SA/Rondonia_example");`

When I try to load this image, I get:
`Image (Error)
Image.load: Image asset 'projects/GLANCE/RESULTS/CHANGEDETECTION/SA/Rondonia_example' not found.`

Is the image gone, or was it never supposed to be there?

**Comment by bullocke** [comment]
@S-AQ It looks like we had the permissions set wrong, I am sorry about that. Would you mind trying again now?

**Comment by S-AQ** [comment]
Hi, thanks for the quick reply. Yes, it works fine now! Thank you
