### ISSUE TITLE
Question about CCDC：when using Landsat and sentinel-2 data to implement the change  detection，I got  very different result.

### ISSUE THREAD

**Issue by cdgaccount** [parevalo/gee-ccdc-tools#4]
hi,
I used the code that is from gee-ccdc-tools . I just change "getLandsat" to "getS2" for the  change detection.I got very different result, like this:
![屏幕截图 2021-09-10 224907](https://user-images.githubusercontent.com/58691599/132873841-db6f7c46-9ef9-45c5-906d-b04f02119036.png)

the landsat code: [link](https://code.earthengine.google.com/b250c48be94b9e6cc824aca9e18dd1f6?noload=1) 
the sentinel-2 code:[link](https://code.earthengine.google.com/116ee8ab8d76d2dbab689a1fea24e5e6?noload=1) 

Please give me advice on any aspect of this.
thank you very much！

**Comment by cdgaccount** [comment]
Now I know the actual time of change.
And the result of change detection using Landsat data is right, the result of change detection using sentintl-2 data is wrong.They are about a year apart.
Why?

**Comment by parevalo** [comment]
CCDC will detect breaks for input datasets of different kinds, but there is never a guarantee that the same breaks will be detected, or that they will be detected at the same time.
