### ISSUE TITLE
Please share your assets

### ISSUE THREAD

**Issue by thanhgis** [parevalo/gee-ccdc-tools#5]
Thanks for your great application and tools. 

Please share your assets, something like (not only) this: var trainingDataPath = 'projects/GLANCE/TRAINING/MASTER/MAPBIOMAS_100K_POINTS_utf8_4_organized_MASTER'

Thanks in advance.

**Comment by parevalo** [comment]
Where did you see that variable referenced? That asset is not part of this repo (or shouldn't be at least) and it is not necessary to run any of the main functions.
