### ISSUE TITLE
Locate 'changeResults' parameter

### ISSUE THREAD

**Issue by ulfboge** [parevalo/gee-ccdc-tools#7]
Dear Dr. Arevalo,
I am trying to implement and learn your Land cover tutorial (API) hand have run into a problem. In the section "Get predictor data for each training point" there is a note stating that the 'changeResults' parameter from the previous section should be specified. I am struggling to figure out what and where that path is and should be. Could you please provide me with some guidance? 

Thank you!

Kind regards,
Johan

**Comment by parevalo** [comment]
Hello Johan,

This refers to the change detection results. You need to specify the path to an asset with the results of the CCDC algorithm, either run by you for your study area (that would be the final output of Part 1 of the tutorial), or available elsewhere (e.g. run by a colleague, or by a different project).
